# apps/server/docker-compose.yml
services:
  db:
    image: postgres:16
    container_name: matercare_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matercare_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: matercare_pgadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # If you want to use a custom domain like matercare.local instead:
      # PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["matercare.local"]'
      # PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin-data: